### ISSUE TITLE
Failed to get token from GitHub.

### ISSUE THREAD

**Issue by prestonvanloon** [target/goalert#1092]
**Describe the Bug:**
I'm getting an opaque error and no idea how to solve it.

**Steps to Reproduce:**
Try to log in with github

**Expected Behavior:**
It works.

**Observed Behavior:**
It doesn't work. Seeing this error: "Failed to get token from Github."

https://github.com/target/goalert/blob/254a9a496f37b73219cf3caa4c4d3eabe1317650/auth/github/identityprovider.go#L130

**Screenshots/Stack Traces:**

![Screenshot from 2020-12-02 15-38-05](https://user-images.githubusercontent.com/7246818/100944570-6e0c7580-34b4-11eb-939a-e1138a54d493.png)

**Application Version:**

v0.26.0

**Desktop:**
linux chrome Version 87.0.4280.66 (Official Build) (64-bit)

**Smartphone/Tablet:**

**Additional Context:**

**Comment by Forfold** [comment]
Do you remember the state of your login prior to this occurring? i.e. Recently clearing auth sessions in profile, logged in normally with a different provider, etc

**Comment by m17ch** [comment]
Hi @prestonvanloon,

I tried reproducing today by configuring a new OAuth app at GitHub and [following our GoAlert configuration documentation](https://goalert.me/docs/developer-getting-started/#github-authentication), but I was able unable to reproduce the failure (auth+login are working, as desired).

Would you mind taking a peek at the documentation link above and make sure the GitHub OAuth app is configured the same way?

Within GoAlert, make sure `Admin` -> `General` -> `Public URL` 
and
GitHub's OAuth App -> `Authorization callback URL`
are pointing to the same TLD (i.e. both use `localhost`).

Let us know if you're still experiencing problems and we can help investigate further - thanks for submitting the issue.

**Comment by prestonvanloon** [comment]
My issue was with a restrictive egress policy in our cluster. Calls to github.com were not allowed. After resolving that, the issue was no longer a concern in my setup.

If there is any actionable item here, it would be to wrap the oauth error for faster debugging. 
I'll leave that up to you, if you want to close this issue as resolved or if you'd accept a PR to wrap the error. 

Thanks!

**Comment by mastercactapus** [comment]
Yes, we should be logging the real error before returning the auth error like we are elsewhere:
https://github.com/target/goalert/blob/254a9a496f37b73219cf3caa4c4d3eabe1317650/auth/github/identityprovider.go#L148

That one I linked should also be changed from Debug to Log. Anywhere we're returning the "friendly" `auth.Error`, from something that went wrong, the return statement should be preceded by a `log.Log`
