### ISSUE TITLE
allow managing users from admin panel

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#1247]
**Is your feature request related to a problem? Please describe:**
It is not currently possible to do anything other than adding users via the CLI for basic auth.

**Describe the solution you'd like:**
Perform the following from within the GoAlert web UI:
- [x] Add users (@dctalbot)
- [x] Delete users (@dctalbot and @KatieMSB)
- [x] Change user roles (@arurao)
- [ ] Allow users to change their password when Basic auth is enabled from Profile
- [ ] Consolidate UI into centralized dashboard - may be out of scope/needs more discussion on design

**Describe alternatives you've considered:**
These steps are only currently possible with direct DB access and knowledge of GoAlert internals.

**Comment by Forfold** [comment]
> - Allow users to change their password when Basic auth is enabled from Profile

This would be a good candidate for #1068
