### ISSUE TITLE
Generic API summary not posting

### ISSUE THREAD

**Issue by JimGwynn** [target/goalert#1346]
When posting an alert with the Generic API using the template
curl -X POST http://goalert.example.com:8082/api/v2/generic/incoming?token=token&summary=DCHELP

The alert is created but the summary is not recorded and the sms message simply says Alert #X

**Steps to Reproduce:**
1. Go to use curl to post to the Generic API
2. Look at the Alert created - the value of summary is missing
3. Look at the SMS message received - The message does not contain the value of summary

**Expected Behavior:**
I expect to see the value of the summary element displayed in the alert and sent via SMS

**Observed Behavior:**
The value of the summary element is missing

**Application Version:**
ubuntu$ goalert version
Version:   v0.26.0
GitCommit: 12a9751416a5ac53aa576954440861883b0111ab (clean)
BuildDate: 2020-11-11T15:47:08Z
GoVersion: go1.15.3 (gc)
Platform:  linux/amd64
Migration: session-last-access-time (#200)

**Comment by m17ch** [comment]
Hi @JimGwynn 

I attempted to reproduce issue by checking out `12a9751` commit and creating an alert locally using an identical call:

`curl -XPOST 'http://localhost:3030/api/v2/generic/incoming?token=XXX&summary=DCHELP'`

![image](https://user-images.githubusercontent.com/23565500/112173916-004f9b00-8bc4-11eb-9499-3d94e83b38a7.png)


This created the alert with the summary "DCHELP" as desired.  I also attempted to create another alert with details populated and that appears to be working correctly, too:

`curl -XPOST 'http://localhost:3030/api/v2/generic/incoming?token=XXX&summary=DCHELP&details=DCHELP'` 

Depending on what shell you are using, you may need to include the singe quotes around the URL & query params (like my examples above).

If that still doesn't do it, would you mind relaying the output of `curl --version` and report what OS you are doing the curl request from?

**Comment by JimGwynn** [comment]
That was it  - Thanks - you can close this
