### ISSUE TITLE
ui/desktop: page-level context menus are hard to find

### ISSUE THREAD

**Issue by Forfold** [target/goalert#1366]
**What problem would you like to solve? Please describe:**
Page-level actions (i.e. Edit rotation) have proven to be confusing/hard to find on desktop. Users need a clear way to manage details pages.

**Describe the solution you'd like:**
Since there can be multiple page-level actions depending on the target, it may be best to simply move these actions out of the toolbar on desktop and above the Header Card:

![Screen Shot 2021-03-29 at 12 17 54 PM](https://user-images.githubusercontent.com/11381794/112888134-d77a4a80-9088-11eb-87a6-e1813af1892d.png)

```
<Grid container>
  {(notices?.length ?? 0) > 0 && (
    <Grid item xs={12} className={classes.spacing}>
      <Notices notices={notices} />
    </Grid>
  )}

  // Move page level actions here

  <Grid item xs={12} className={classes.spacing}>
    <Card>
      <CardContent>
        <Grid container spacing={2}>
          <Grid item xs={isDesktopMode(width) && links ? 8 : 12}>
            {icon && <div className={classes.iconContainer}>{icon}</div>}
            <Typography
              data-cy='details-heading'
              className={classes.mainHeading}
              component='h2'
            >
              {title}
            </Typography>
            . . .
```

**Describe alternatives you've considered:**
- Change icon from `...` to a gear icon
- For pages with only a few actions, it would make sense to just render flat without being behind a menu (requiring an extra click from the user)

**Additional context:**
The current context buttons for a given details page can be seen in the top right of the following screenshot:
![Screen Shot 2021-03-29 at 11 57 01 AM](https://user-images.githubusercontent.com/11381794/112886192-718cc380-9086-11eb-94af-ba38c18d622d.png)

**Comment by mastercactapus** [comment]
I feel like these might make sense to be inside the header card, wouldn't they? At least with favorite, edit, and delete -- they seem to be actions/options for the content in the main card directly.

**Comment by Forfold** [comment]
True, I could go either way!

**Comment by Forfold** [comment]
I was thinking @mastercactapus, if we have the controls above the card, we could then further increase visibility in the main content by having the page breadcrumbs above the card as well, aligned to the left. This then allows us to free up more vertical space in the sidebar since we can then replace that space with the GoAlert logo

**Comment by mastercactapus** [comment]
I feel like that would blur the intent/purpose of having the title/nav bar up top. We could have the sidebar go all the way up if we wanted. In the case of the alerts list, it makes sense to use that space for the list controls/editing, but it makes things a little more confusing IMO if we put them there. It might also be a case where we change things between mobile and wide. Maybe mobile should keep the menu in the top, and wide moves controls to cards.

Schedules, for example, if I were to want to edit the name or details, I'd expect it to be with that, to the left of the quick links:
![image](https://user-images.githubusercontent.com/595010/114905216-52a86400-9dde-11eb-945b-7279b9642681.png)


Kind of like how we put the event log controls with the relevant content:
![image](https://user-images.githubusercontent.com/595010/114905405-897e7a00-9dde-11eb-972d-bebd525f2395.png)

Likewise, if we ever decided to move away from FABs for widescreen, I'd look for the "+" button for lists to be in the individual cards:
![image](https://user-images.githubusercontent.com/595010/114905706-dc583180-9dde-11eb-9271-8c4eb6989e52.png)
![image](https://user-images.githubusercontent.com/595010/114905785-f3971f00-9dde-11eb-9479-da5eb9a6ab0b.png)

**Comment by mastercactapus** [comment]
OTOH if we follow material design, icon actions should be in the lower right:
https://material.io/components/cards#anatomy:
![image](https://user-images.githubusercontent.com/595010/114906281-7fa94680-9ddf-11eb-99dd-1fd0ec11f8c7.png)

**Comment by mastercactapus** [comment]
That could at least move edit, delete and the favorite icon into the card representing the schedule, for example. The filter icon is a little different, maybe that one should remain page level, or move to the calendar card (for schedules). Not really sure

**Comment by Forfold** [comment]
True! We totally should be following the mui design spec for this type of thing. Primary actions would be "Edit" and "Delete", with secondary icons on the right being everything else (pretty much just favoriting at this point). I think the filter icon still make sense in the toolbar, but I'll read up on the standards for rendering lists as well.
