### ISSUE TITLE
Configure admin username and password with env vars

### ISSUE THREAD

**Issue by xordspar0** [target/goalert#15]
**Problem:**
I would like to be able to configure the admin user and password before starting up the Docker container.

**Describe the solution you'd like:**
The admin user name and password could be configurable via environment variables.

**Describe alternatives you've considered:**
Maybe an alternate init.sql file could be provided by the user.

**Comment by mastercactapus** [comment]
The all-in-one container is meant to be a demo-only container (thus the static credentials), as there is no great way to ensure data persistence, upgrades, etc...

Having said that, if you did want to customize the image, you should be able to create a Dockerfile that replaces `init.sql`.

```Dockerfile
FROM goalert/all-in-one
COPY init.sql /bin/
```

Then when the new container image starts, it will use the new `init.sql` file instead.

Let us know if that would work, or if you can provide some more info about your use case.

**Comment by xordspar0** [comment]
I see, I didn't realize that the all-in-one container was just a demo. The Getting Started guide looks good. 👍
