### ISSUE TITLE
ui: CardCollection reusable component alternative to FlatList

### ISSUE THREAD

**Issue by Forfold** [target/goalert#1518]
**What problem would you like to solve? Please describe:**
Craft a reusable component of a [collection of cards](https://material.io/components/cards#card-collections) that can be used in place of FlatList items as needed

**Describe the solution you'd like:**
A CardCollection version of FlatList with minimal API differences for the developer (aside from supplemental features)

**Additional context:**
Will be useful in rendering actions in relevant containers

**Out of Scope:**
Complicated things like drag and drop. Data and action container display only

**Comment by m17ch** [comment]
Group discussed this and determined it is not something that we'd likely get to in the immediate future -- will re-open/revisit in the future, if appropriate.
