### ISSUE TITLE
Notification when user on-call changes

### ISSUE THREAD

**Issue by bherbst** [target/goalert#1973]
**What problem would you like to solve? Please describe:**
Our schedules can change fairly frequently as individuals join or leave our team. While we appreciate the ability to subscribe to a schedule to get on-call shifts on individuals' calendars, shifts to the schedule often go unnoticed and catch people by surprise.

**Describe the solution you'd like:**
If my next shift on a schedule has moved I'd like to receive a notification (Slack, email, whatever) that tells me when my next shift is.

I don't think this needs to happen if my next shift stays the same, even if the rest of the schedule has changed.

**Describe alternatives you've considered:**
Whoever is adjusting the shift can blast out a message to everyone in the schedule, but then everyone still needs to go in and check their shift. We have the power to do much better 😄

**Comment by arurao** [comment]
Hello! We have discussed this as a team and for MVP, we are thinking of sending slack notifications before an on-call shift starts, maybe like 24 hours before the start time, to be able to provide users with a reminder functionality. Is this something that might be useful for your use-case?

**Comment by bherbst** [comment]
I think that's a great feature, but doesn't quite address the issue I'm describing.

For example, it's currently January. My team has week-long shifts. Say I'm planning an event with friends for the middle of February. I'm on call for a week at the end of February, so that should be fine! Unfortunately this week one of my coworkers leaves us, so the entire schedule shifts up a week, and now my on-call shift conflicts with the event I had planned.

I would like to know about this _now_ (when the change to my shift happens) so I can change my plans, not the day before the event I had planned.

**Comment by bherbst** [comment]
Even if I can change that notification period from 24 hours to something like a week, I'd still rather know _when the change to the schedule happens_ instead of relying on a fixed notification window before my shift.

Different types of events (travel, impromptu game nights, etc.) require different amounts of planning and reaction to either change the event or find someone to cover an on-call shift, so I prefer to know ASAP so I can react appropriately.

**Comment by bherbst** [comment]
Still would love to see this 🙏  (sorry stalebot)

**Comment by Ranbato** [comment]
I would like to be able to set a notification window as well as an additional scenario.

1. Notify impacted people when the schedule shifts
2. When the next on-call starts also list upcoming shifts. e.g. Alex is starting on-call and Sam is on-deck for the next rotation
