### ISSUE TITLE
MaxSummaryLength in summary alert field

### ISSUE THREAD

**Issue by deepminimal** [target/goalert#2053]
**What problem would you like to solve? Please describe:**
Hello! We have "summary" field with length more than 118 symbols. Example:
![image](https://user-images.githubusercontent.com/18044597/145173904-bb2c1182-9e45-48a5-bd6e-afc9f29e7b40.png)

MaxSummaryLength = 118 setting in code by const https://github.com/target/goalert/blob/master/alert/alert.go#L14
**Describe the solution you'd like:**
Can you set MaxSummaryLength by parameter in setting file or environment?

**Comment by Forfold** [comment]
Could this be an appropriate use case to add to the system limits config? It would make the setting available from the admin page. @mastercactapus

**Comment by Forfold** [comment]
@deepminimal We decided we're going to up the limit of the summary to 1024 (1KB) as the current limit is a bit old and out of date.
