### ISSUE TITLE
Alerts are not getting closed for alerts from Grafana8

### ISSUE THREAD

**Issue by kiran3394** [target/goalert#2077]
**Describe the Bug:**
Alerts are not getting closed in goalert even after resolving in Grafana8.

**Steps to Reproduce:**
1. Create an alert rule in Grafana (8.1.2) and corresponding notification policy with contact point as goalert incoming webhook.
2. When alert rule goes to alerting state, we get alert in goalert.
3. When the alert get resolved in Grafana, alert is not getting closed in goalert.

**Expected Behavior:**
Alerts should be closed after it get resolved in Grafana (8.1.2)

**Observed Behavior:**
Alerts are not getting closed in goalert even after resolving in Grafana8.

**Application Version:**
Grafana - 8.1.2
Goalert- v0.29.0

**Comment by kiran3394** [comment]
We have done patching to fix it: 
In grafana.go
```
// To handle closing of alerts coming from Grafana-8
		enable_grafana8 := os.Getenv("ENABLE_GRAFANA8")
		if strings.EqualFold(enable_grafana8, "true") {
			g.Message = strings.ReplaceAll(g.Message, "**Firing**", "")
			g.Message = strings.ReplaceAll(g.Message, "**Resolved**", "")
		}
```

**Comment by mastercactapus** [comment]
Just working on the review of a PR fixing this, it looks like Grafana's new payload includes a version number so once merged & released it should work automatically with no ENV var required. Thanks for the report!
