### ISSUE TITLE
Supporte 'application/json' content type in incoming webhook

### ISSUE THREAD

**Issue by pandey-adarsh147** [target/goalert#2092]
**What problem would you like to solve? Please describe:**
incoming webhook should also support `application/json` type instead of just `application/form-data`

**Describe the solution you'd like:**
Submit json format data should be accepted.

**Comment by mastercactapus** [comment]
Thanks for opening a PR, I think this would be helpful. We may have some time next week to wrap it up if you don't get to the requested changes.
