### ISSUE TITLE
ui/metrics: add tta, ttc, escalation count to UI

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#2124]
**Description**

Requires #2123

Add time-to-ack, time-to-close, and escalation counts to the Alert Metrics graph for services. Additionally, add the new data points to the table and CSV export function.

- Ability to export alert CSV with time-to-ack, time-to-close, and escalated? columns
- Ability to view new metrics on the graph

TODO: Feedback on how it should be displayed (i.e., bar/line, one at a time?)

**Comment by KatieMSB** [comment]
Closing in favor of #2313
