### ISSUE TITLE
partial text match search

### ISSUE THREAD

**Issue by jmccann** [target/goalert#2125]
**What problem would you like to solve? Please describe:**
_A clear and concise description of what the problem is._

Currently when you search GoAlert it does a full word match.  e.g. If searching services for a service named slingshot, `sling` will not find the service.  You need to fully enter `slingshot` to find the service.

**Describe the solution you'd like:**
_A clear and concise description of what you want to happen._

I want a partial string search to return expected results.  e.g. if I search `sling` I would see a list that includes `slingshot`.

**Additional context:**

**Comment by mastercactapus** [comment]
The current search is basically exposing an implementation detail, namely the type of indexing we currently have. One of the constraints we place is limiting the number of extensions we rely on (in Postgres). It's kind of been a TODO to implement something a bit more flexible and portable.

When complete, that should look like case-insensitive prefix matching for all types, like what we have for user search currently.

---

Notes from a recent discussion about implementation:
- Package to manage managing Name->ID mapping
- Where applicable, perform a name filter in-memory against a cached list
- Do additional filtering against the list of matched IDs as we do today

Implementation thoughts/notes:
- store ID & Name in memory
- reload every 15 min
- update cache with any recently changed rows at shorter interval (3 sec?)

Risks:
- Running an old version of GoAlert to update the name of something (that doesn't update the row timestamp) could result in stale search result data for up to 15 minutes on a new version of GoAlert

**Comment by Forfold** [comment]
One option is to only search by name to make the query a bit more light weight.

**Comment by tony-tvu** [comment]
https://github.com/target/goalert/pull/2525
