### ISSUE TITLE
debt: remove unmaintained tracing code

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#2158]
Tracing code was added with spans for debugging things like GraphQL & DB calls that we have other tools for now. This code hasn't been maintained for a long time and just adds noise, complexity, and build time.

We should pull it out and remove the dependencies:

- `cloud.google.com/go`
- `contrib.go.opencensus.io/exporter/jaeger`
- `contrib.go.opencensus.io/exporter/stackdriver`
- `go.opencensus.io`

---

If requested we can re-introduce it in the future in a planned and maintainable way.

**Comment by alishahwee** [comment]
Hey, could I take this on?

**Comment by mastercactapus** [comment]
@alishahwee Absolutely! It will touch a lot of files, so feel free to break it into pieces/multiple PRs if you run into tricky bits.
