### ISSUE TITLE
OIDC redirect_uri not using Public URL

### ISSUE THREAD

**Issue by mikementzmaersk** [target/goalert#2256]
**Describe the Bug:**
Hi - Great application, so thanks for continuing to improve it.

We've noticed that during an OIDC auth flow, when the url is constructed that takes you to your OIC provider...
 (eg, https://login.microsoftonline.com... &redirect_uri=https%3A%2blahblah )
 
... the redirect_uri passed to the OIDC provider is not what we have set the "Public URL" to via Config admin page.

This manifests itself when we have goalert behind a proxy

**Steps to Reproduce:**

1. Configure General > Public URL to URL1
2. Navigate to Goalert homepage using URL1 which routes to go alert via a proxy (which we'll call URL2)
3. Perform an oidc flow, get redirected to provider, see the redirect_uri is set to URL2, not URL1 from the config.
4. Different to what is documented, which states it should use what is in the config.

**Expected Behavior:**
request_uri starts with the Public URL

**Observed Behavior:**
request_uri start with the URL that the proxy communicated with

**Application Version:**
0.29

**Comment by mfominov** [comment]
If your proxy url is goalert.example.com and real app url is goalert.app.example.com yeap problem will be.
I faced same problem with goalert in k8s(ingress) behind nginx.

**Comment by skob** [comment]
I think main problem is here:
https://github.com/target/goalert/blob/5e278bacae48565a5249bcc80ce195ef085d2c56/auth/handler.go#L363
callback url is generated from current request url, not from PublicUrl.

So if you use proxy , you can define headers for pointing on right url (URL1). In case of nginx it is something like
```
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

```

**Comment by mikementzmaersk** [comment]
Thanks @skob - yes that certainly explains the behaviour - the nginx snippet was also beneficial as a means to override the request url with the desired public url. 

The following k8s nginx ingress annotation seemed to do the trick, which flows down into NGINX config as a replacement for proxy_set_header Host $host..

nginx.ingress.kubernetes.io/upstream-vhost: URL1

Issue Resolved by changing proxy conf :-)
