### ISSUE TITLE
Dependencies between service  

### ISSUE THREAD

**Issue by mfominov** [target/goalert#2257]
Thx for this project.

It will be nice to create dependencies between service.
As example if db service is down that meat app service is down to.

That do u think?

**Comment by Forfold** [comment]
If you're looking for multiple services to notify the same people, we would recommend using the same escalation policy for both of these services. GoAlert doesn't really have a concept of a service being "up" or "down", they just send out notifications.

You can also check out service labels, which are a way to group services together.

**Comment by mfominov** [comment]
@Forfold thx, i'll look at labels tomorrow.
