### ISSUE TITLE
invalid value for 'Username' - dot character to the allowed characters

### ISSUE THREAD

**Issue by bndrv** [target/goalert#2325]
I'm testing a goalert to apply in our company. We use the username with a dot. For example, <bondarev.a>. It has historically happened and we are not ready to change the nicknames of 200+ employees.

So we can't use goalert as it doesn't allow to specify such username - "Error: add basic auth entry: invalid value for 'Username': can only contain lower-case letters and digits".

In my opinion, it's worth adding a dot character to the allowed characters. Since this is a strong limitation for the distribution of goalert.

Thank you!

![image](https://user-images.githubusercontent.com/73041992/164721948-971b5c24-7567-4f1c-8688-650577506c93.png)

**Comment by mastercactapus** [comment]
seems reasonable to me
