### ISSUE TITLE
Create Alert Dialog cannot be completed

### ISSUE THREAD

**Issue by phucnv282** [target/goalert#2370]
**Steps to Reproduce:**
Create a new Alert on UI

**Expected Behavior:**
The new alert was created successfully and Create Alert Dialog closes

**Observed Behavior:**
Create Alert Dialog always retry after confirming

**Screenshots/Stack Traces:**
![Screenshot from 2022-05-06 14-29-43](https://user-images.githubusercontent.com/33126800/167087853-d9202fbb-123a-490d-9512-a23d4c828330.png)

**Application Version:**
`
$ latest commit
...
`

**Comment by mastercactapus** [comment]
This seemed to be an issue with apollo which should now be fixed in master as we're no longer seeing it after #2356 was merged; @phucnv282 can you confirm?

**Comment by mastercactapus** [comment]
Closing as we are no longer able to reproduce in master after the fixes in #2356 were merged. Reopen if it is still an issue
