### ISSUE TITLE
admin: message log start/end time don't reset on nav

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#2414]
**Describe the Bug:**
The date filter fields don't reset after navigation.

**Steps to Reproduce:**
1. Go to Admin -> Message Logs
2. Set the start time filter to the future
3. Click on Message Logs from the nav bar
4. The filter resets, but the input field does not

**Expected Behavior:**
The input field should reset as if the page were reloaded.

**Observed Behavior:**
The input field preserves the old value, even though it doesn't match what is being displayed.

**Comment by cmarquis** [comment]
@mastercactapus I think this may have been solved with other changes. Not seeing this behavior on the current master branch.

**Comment by mastercactapus** [comment]
Yeah, it looks to have been fixed from at least v0.30.1 if not earlier
