### ISSUE TITLE
ui: override form closes when opened from calendar

### ISSUE THREAD

**Issue by Forfold** [target/goalert#2439]
If opening the override form from the calendar, after a few seconds the dialog closes. This appears to be due to polling.

**Comment by cmarquis** [comment]
@Forfold do you think this has been fixed as a part of other changes? Not seeing the issue currently by clicking the override button on a schedules calendar.

**Comment by Forfold** [comment]
Yep! This looks to be working on my end too. I'm thinking maybe it got resolved as we've been moving some components over to `urql` instead of `apollo`. I'll go ahead and close this issue. Thanks!
