### ISSUE TITLE
ui/simplelistpage: use Component type for createForm

### ISSUE THREAD

**Issue by Forfold** [target/goalert#2458]
In a [PR](https://github.com/target/goalert/pull/2434/files#diff-5d4674a38b7350eee6f7fe13989e3400c9403a96721491c543f3e34a22b59c1eR33) (#2434) converting a Dialog component to Typescript rendered as a child of `SimpleListPage` component was forced to set the `onClose` prop to optional, because in `SimpleListPage` we clone the passed Dialog component and then append the onClose property to props.

We should think about setting `onClose` to required for our Dialog components, which would require `SimpleListPage` to accept a Component instead of a JSX.Element.

E.g.

```
<SimpleListPage
  createForm={<RotationCreateDialog />}
/>
```

would change to

```
<SimpleListPage
  createDialogComponent={RotationCreateDialog}
/>
```

and we could add a render prop option, too, if some components need to pull off some shenanigans in scope as well:
```
<SimpleListPage
  renderCreateDialog={(props) => <RotationCreateDialog foo={bar} {...props} />}
/>
```

**Comment by tony-tvu** [comment]
https://github.com/target/goalert/pull/2467

**Comment by KatieMSB** [comment]
Completed in #2467
