### ISSUE TITLE
GoAlert with OIDC authentication, users with same name not being identified correctly while adding the users in escalation policy, rotations

### ISSUE THREAD

**Issue by sivtechrepo** [target/goalert#2496]
**Describe the Bug:**
GoAlert with OIDC authentication, users with same name not being listed, only one entry is listed and all the others are not listed. Its fixed in [Issue](https://github.com/target/goalert/issues/2250), 

However, while adding the users in to the escalation policy or rotations with same name cannot be identified correctly.
It just simply shows multiple times and not making it clear to choose the right one.

**Steps to Reproduce:**
1. Go to Escalation Policy 
2. Edit Escalation steps and try adding users
3. See error, same name will be displayed multiple times and making it difficult for the customer

**Expected Behavior:**
All the entries of the search need to display the name along with email address so user can select the appropriate one for the same name cases

**Observed Behavior:**
Only the `name` is being repeated for the `same name` cases, there are two types of user select, single user select and multi user select.

![image](https://user-images.githubusercontent.com/9267000/178250302-beb14506-1524-4f0f-a9e4-83e2dce03d3e.png)
![image](https://user-images.githubusercontent.com/9267000/178250337-b72f4615-f59f-4cf5-a24a-aea2d7eff1e0.png)

**Screenshots/Stack Traces:**
If applicable, add screenshots and/or stack traces to help explain your problem.

**Application Version:**
0.29.0

**Desktop:**
 - OS: [e.g. MacOS, Windows]
 - Browser [e.g. Chrome, Safari]
 

**Additional Context:**

If the solution includes the email along with name just while displaying, would be easier for users to select the right users as shown below,
<img width="1595" alt="MicrosoftTeams-image (14)" src="https://user-images.githubusercontent.com/9267000/178254225-8a71a6ab-b541-4e57-9b7e-e0dab357cee2.png">

**Comment by mastercactapus** [comment]
This makes a lot of sense, maybe we can show the email as secondary text under each name to prevent the items from running long/wide.

Also, calling out to scope this specifically for cases where two separate people have the same name and not duplicate entries for the same user that can happen from changing OIDC login ids.

**Comment by sivtechrepo** [comment]
thank you for fixing this. @mastercactapus @tony-tvu
