### ISSUE TITLE
Rotations: Problem removing user from rotation

### ISSUE THREAD

**Issue by m17ch** [target/goalert#2543]
**Describe the Bug:**
Rotations with at least 2 users, cannot remove last user if active.

**Steps to Reproduce:**
1. Create a rotation with at least 2 users
2. Set the 2nd person active
3. Remove the 2nd person from rotation

**Expected Behavior:**
First person in list remains and becomes active in rotation.

**Observed Behavior:**
The confirmation dialog displays "Confirm" and then "Retry" but never goes away.  The user is not removed from the rotation.

**Application Version:**
```
<meta http-equiv="x-goalert-version" content="v0.28.0-2861-g31cdeb056" />
<meta http-equiv="x-goalert-build-date" content="2022-07-28T05:21:17Z" />
<meta http-equiv="x-goalert-git-commit" content="31cdeb056175f2e67495e9c061551ec74bc82de3" />
```

**Comment by mastercactapus** [comment]
+ Add a test case in Cypress for this, in addition to the one that's there
Might be a good case to look at #2499

**Comment by mastercactapus** [comment]
Still an issue as of 5071dbd2df08ff5c53d187e898d468d76bfdf561
