### ISSUE TITLE
ui: heartbeat monitor page not refetching on create

### ISSUE THREAD

**Issue by Forfold** [target/goalert#2581]
**Describe the Bug:**
When creating a heartbeat monitor, or when posting to its endpoint, the page doesn't update until you refresh. This is presumably because polling isn't configured/is disabled, but should be so users can see live updates.

**Comment by mastercactapus** [comment]
This sounds like a regression - it should update every 15 seconds or immediately if you click away and back to the tab

**Comment by Forfold** [comment]
Hmm, maybe I wasn't waiting long enough then, since the other pages are set to show changes within 3 seconds

**Comment by mastercactapus** [comment]
Were you able to confirm if this is still an issue? The apollo components are 3 seconds; the urql ones use the new behavior (unless they specifically run at a more frequent rate)

**Comment by Forfold** [comment]
looks like polling works, but the main issue is the cache not optimistically updating the list if successful (or refetching it immediately). ill update title
