### ISSUE TITLE
Self reset password function for user

### ISSUE THREAD

**Issue by qdu291** [target/goalert#2667]
Dear Team,

Is there reset password function available? As I check, there is no way to reset password on GUI.
If this function still not implemented, kindly consider and enhance.
Thank you.

**Comment by mastercactapus** [comment]
Not currently; most use cases are using OIDC or GitHub auth, so the basic user/path auth has gotten a little stale. This is a gap to be addressed. I think as a first step having a change password on the profile page and maybe a way for an admin to reset a user's password.

"Forgot Password" flows will be tricky since profile emails aren't required/validated/used.

**Comment by jonathanspw** [comment]
This would be an excellent feature.

**Comment by razor-1** [comment]
Definitely would like to have this - especially for the admin user to change its own password. It's good to have an admin user not reliant on external systems to get in, and right now it's not easy to change that user's password.

**Comment by wtc-jeff** [comment]
+1 for this, please.

**Comment by Forfold** [comment]
Starting on this work- should admins have the capability to reset a user's password (that's not their own)?

**Comment by razor-1** [comment]
I'd vote for allowing admins to reset other user's passwords. Thank you

**Comment by jonathanspw** [comment]
> Starting on this work- should admins have the capability to reset a user's password (that's not their own)?

I'd vote yes, allow admins to reset other user's passwords.

**Comment by wtc-jeff** [comment]
Would it be possible to have new user creation be sent an account confirmation link and an option to set their initial password instead of it being set by the person adding the account?

**Comment by Forfold** [comment]
@wtc-jeff I think new user creation by people other than admins should probably sit in its own ticket- I can see that being its own body of work. I imagine it will follow a similar flow of needing a verification email when you forget your password if you're logged out.
