### ISSUE TITLE
ui: make primary create buttons more visible

### ISSUE THREAD

**Issue by Forfold** [target/goalert#2693]
We often get user requests saying they don't know how to create or add something. Material's design focuses on a mobile-first design, but I think in this case the Fab button that we're currently using is too far out of the way for most desktop users.

**Comment by mastercactapus** [comment]
I agree; maybe an ADD button in the Contact Methods and Notification Rules header as a first step? It seems to come up a lot

**Comment by Forfold** [comment]
Agreed, I was thinking of maybe moving into the cards for details pages actions. Not sure on the list pages- we should get together and brainstorm

**Comment by Forfold** [comment]
acceptance criteria:

- move profile fabs to contact method and notification method cards in top right
- include icon with relevant text (e.g. "+ ADD" or "+ CREATE")
- move list page fab buttons to top right of list
  - move search bar to the left

**Comment by Forfold** [comment]
Sections remaining:

- [ ] rotation add user
- [ ] escalation policy add step
- [ ] Match contact/notification buttons styling to rest of app (incl. text, style button as contained w/ primary color)
