### ISSUE TITLE
Dev: Switch to GolangCI-Lint

### ISSUE THREAD

**Issue by ethan-haynes** [target/goalert#2714]
**What problem would you like to solve? Please describe:**
We want to switch from using multiple checks for linting to use a single Golang linting tool.

**Describe the solution you'd like:**
Be able to run `make check-go` which should execute the golangci-lint command. With error check disabled (out of scope).

Follow Up Issue:
#2579

**Comment by mastercactapus** [comment]
Resolved by #2723
