### ISSUE TITLE
Escalation policy auto-created while creating a new Service is not added to favourites

### ISSUE THREAD

**Issue by sivtechrepo** [target/goalert#2724]
**Describe the Bug:**
Escalation policy is created automatically if the escalation policy is not selected while creating the new service

**Steps to Reproduce:**
1. Go to Service
2. Click on Create a new Service
3. View the service created, it's favorited  
4. Click on the escalation policy created 

**Expected Behavior:**
An escalation policy was created while creating the service, it's not favorited and it supposed to be favorited 

**Observed Behavior:**
 An escalation policy was created while creating the service, it's not favorited
**Screenshots/Stack Traces:**
If applicable, add screenshots and/or stack traces to help explain your problem.
Service is on favorite when its created 
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/9267000/206129560-cd769134-1de3-4448-81f2-723629bc7ed9.png">
the escalation policy created along with service is not on favorite
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/9267000/206129640-14fac937-780c-4d18-8c16-907d72e19065.png">
It has to be favorited as shown below once created,
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/9267000/206129818-6ed90d23-0972-46bf-b839-db7544202e33.png">

**Comment by rajeshggwp** [comment]
I can work on this

**Comment by sivtechrepo** [comment]
thank you @rajeshggwp @mastercactapus
