### ISSUE TITLE
slack on-call schedule notification assignments order is random

### ISSUE THREAD

**Issue by Forfold** [target/goalert#2784]
when we send out on-call notifications when the on-call person changes for an assignment, if there are multiple changes at once, the message is not sorted. As a user, it would help if they were.

It would also help if the assignment name was prepended before the user's name if there is more than one assignment being updated at once.

e.g. (Primary GoAlert) Nate and (Secondary GoAlert) Ashok are on-call for GoAlert.

**Comment by mastercactapus** [comment]
The name of each schedule (as a link) is printed for each group of on-call users at the end. A schedule with the name "Primary GoAlert" will have users listed, followed by "Primary GoAlert" as a link to the schedule. Having a primary and secondary schedule will already give this behavior; naming them primary/secondary for clarity would be reflected in the on-call messages.

Multiple assignments being updated at once will send a separate message for each.

As for the user sorting, that was indeed missed but an easy fix.

**Comment by Forfold** [comment]
This is more around the name of the assignment itself being displayed as well for additional context, rather than the schedule name as a whole. This message is a result of two different rotations changing at the same time:

![Screen Shot 2023-01-16 at 8 15 11 AM](https://user-images.githubusercontent.com/11381794/212729677-d0a16d39-c849-4386-ae2a-93a59940b9cf.png)

**Comment by mastercactapus** [comment]
I see, in the future rotations will be going away and replaced with a multi-user assignment on a schedule directly, so I don't think it would make sense to add the rotation name.

Also, overrides & temp schedules don't have names either so I'm not sure there will be useful context to share -- a schedule will be the smallest named unit above the users themselves.
