### ISSUE TITLE
make active alert cap more obvious

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#2869]
**What problem would you like to solve? Please describe:**
There is a system-wide limit (admin configurable) on the number of active/unacknowledged alerts per-service. When a service hits this limit, it isn't obvious outside of the API call that there could be an issue creating new alerts.

**Describe the solution you'd like:**
A notice on a service, and any alert details pages, when a service is at or near the limit.
- @ >= 90% display as warning
- @ >= 100% display as error (since no new alerts will be accepted)

**Describe alternatives you've considered:**
The system works as intended currently, but with the cost of admin and end-user time to determine when this happens.

**Comment by Forfold** [comment]
I went with 75% for the warning just to be safe in the above PR ^^
