### ISSUE TITLE
slack DM: status updates not working

### ISSUE THREAD

**Issue by Forfold** [target/goalert#2889]
**What problem would you like to solve? Please describe:**
When an alert is initially created, a Slack DM is sent. However, if the alert is modified, such as an update in the status, there is no update to the Slack DM for users to see.

**Describe the solution you'd like:**
Implement the ability for GoAlert to send status updates to Slack DM notifications.

**Describe alternatives you've considered:**
N/A

**Additional context:**
N/A

**Comment by mastercactapus** [comment]
Notes for reference:
- Seems to happen pretty reliably on a per-user basis; either works or it doesn't
