### ISSUE TITLE
auth: create user keeps transaction open while calculating bcrypt hash

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#2985]
**Describe the Bug:**
When an admin creates a user using the GraphQL mutation, a transaction is started to insert the new user, and to insert the auth info (user/pass-hash) for the new user. The bcrypt hash is calculated during this transaction which keeps the connection open longer than necessary.

This also becomes a more significant issue if the available compute resources cannot compute the hash faster than the transaction timeout, resulting in an "Unexpected error" to the UI and "idle-in-transaction timeout (SQLSTATE 25P03)" in the logs.

**Steps to Reproduce:**
1. Create a user via GraphQL
2. Optionally, set the bcrypt value high, or add a `time.Sleep` to observe timeout

**Expected Behavior:**
The DB transaction should only be open to store the data (calculations should happen before).

**Observed Behavior:**
The DB transaction is held open during the calculation.

**Comment by tong-bluehill** [comment]
For workaround, beside using master branch, can I set a longer timeout value?
