### ISSUE TITLE
Scheduling granularity

### ISSUE THREAD

**Issue by jkennedyOM** [target/goalert#30]
**Describe the solution you'd like:**
I would like to define business hours for the schedule (e.g. 8am-6pm).
I would also like to define a schedule increment shorter than 1 day that rotates during business hours. (e.g. 60m, 4h)

**Comment by Auchindoun** [comment]
Hey @jkennedyOM, we actually support these features already. Let me know if there is something I'm missing.

From a schedule, you can edit when the schedule is active by visiting its "Rules" page. From here you can edit your assignment and specify the hours you would like it to be active; in your case, from 8am to 6pm:

![image](https://i.imgur.com/kzecsuR.gif)

---

You can also change a rotation to rotate as often as hourly. This can be done either when you create the rotation, or while editing:

![image](https://i.imgur.com/o7URHeB.gif)

**Comment by jkennedyOM** [comment]
Thanks! I guess I overlooked it in the interface.
