### ISSUE TITLE
Ability to Record Alert Usefulness (noise)

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#3003]
**What problem would you like to solve? Please describe:**
Currently, there is no way to differentiate between actionable alerts and false positives within GoAlert. It would be beneficial to have a mechanism to capture and report on the usefulness of alerts to improve response efficiency.

**Describe the solution you'd like:**
- Allow users to mark alerts as one of three states: actionable, false positive, or none (default).

**Describe alternatives you've considered:**
- Teams can manually review alerts regularly, but this may not provide the same level of context and efficiency as marking alerts in the moment.

**Out of Scope:**
- Implement a reporting feature that provides an overview of alerts in each of the three states to help teams identify trends and improve alert management.

**Additional context:**
- This feature would help teams better understand the effectiveness of their alerting system and identify areas for improvement.

**Comment by mastercactapus** [comment]
MVP notes:
- Thumbs up/thumbs down buttons (on right side of alert details, actions move to left)
- Buttons have tooltips giving examples: Down=false positive, non-actionable, flapping/auto-closed quickly, not enough info; Up=customer impact, actionable, good information
- impl hint: create a new table with alert ID and sentiment (as int +/- 1) add `rating` field to Alert in schema, defaults to `0`

Next steps (MVP+1):
- update alert metrics table & graph to include rating info
- possibly list recent un-rated alerts
- a note/comment field for down-rated alerts

**Comment by Forfold** [comment]
Adding reporting to it's own issue
