### ISSUE TITLE
Add support for full schedule calendar subscription

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#3061]
**What problem would you like to solve? Please describe:**
Currently, users can generate a calendar subscription for a single schedule in GoAlert, but it only includes their own shifts. This has led to requests for the ability to see all team members' on-call shifts in the calendar subscription.

**Describe the solution you'd like:**
Support should be added to allow calendar subscriptions to include all users' shifts on a specified schedule, allowing visibility of the entire on-call schedule in external calendar applications (e.g., Google Calendar).

**Describe alternatives you've considered:**
An alternative would be to manually create calendar events for all team members' shifts, but this can be time-consuming and error-prone.

**Additional context:**
This feature request has been prompted by community feedback and similar requests over time.

**Comment by mastercactapus** [comment]
This would also help view team schedules on mobile devices since the GoAlert UI does not support a calendar view there; users could subscribe using a mobile calendar app to view team schedules from their phones.

**Comment by wtc-jeff** [comment]
+1 for this feature.  We have other departments that would like to see who is on call and a calendar subscription showing the schedule would solve this for us.

**Comment by Derekt2** [comment]
This would help the CTI team on security so we could see who is on shift easily within outlook from our shared calendar.
