### ISSUE TITLE
Single user calendar view across schedules

### ISSUE THREAD

**Issue by KellyMerrick** [target/goalert#3164]
For users who are in multiple rotations, such as `primary` and `secondary`, it can difficult to visualize availability or on-call coverage for a specific user.

It would be nice to have a calendar view which consolidates all active schedules for just a single user; accessible perhaps via another `quick link` or calendar tab on a specific user's page.

The current method to get around this is to have multiple side-by-side tabs, one for each schedule, but this also shows all other users/overrides and can get messy quickly.

**Comment by Forfold** [comment]
Taking a look at this issue 👀 

My proposed schema addition is:

<img width="493" alt="Screenshot 2023-08-08 at 12 33 45 PM" src="https://github.com/target/goalert/assets/11381794/c7684431-882f-4361-8f5b-2ca1b18e430e">

<img width="192" alt="Screenshot 2023-08-08 at 12 33 57 PM" src="https://github.com/target/goalert/assets/11381794/024743b3-6581-413a-ab20-aaf7946ac4f9">

then with this, enhancing the `oncall.state.CalculateShifts` function to accept a third `userID string` parameter to filter by. The graphql query function will handle setting the state up, by calling any stores as needed, then calling CalculateShifts.

example state:
```
st := state{
		rules:      rules,
		overrides:  overrides,
		history:    userHistory,
		now:        now,
		loc:        tz,
		tempScheds: tempScheds,
	}
```
