### ISSUE TITLE
Alerts metrics for interval "month" does not match with the intervals "day" and "week"

### ISSUE THREAD

**Issue by dkangala** [target/goalert#3252]
**Describe the Bug:**
Total count of alerts displayed in the past 31 days, with "interval = days", is 9. When we change "internal" to "week", the total count displayed is 9 (as expected). But, when we change interval to "month", the total count displayed is 1 (which is "not" expected).
<img width="898" alt="image" src="https://github.com/target/goalert/assets/6043209/b5648560-015b-4762-aee9-47bb63868377">

<img width="898" alt="image" src="https://github.com/target/goalert/assets/6043209/9f276c6c-84b7-44d1-af97-0d767dd335e5">

<img width="898" alt="image" src="https://github.com/target/goalert/assets/6043209/169a264f-e4f7-4b96-b21b-59a9a2d1013e">

**Steps to Reproduce:**
1. Go to "Services" and select any service
2. Click on "Alert Metrics" in quick links
3. Select "Data Range = Month" and change the "Interval" to "Day / Week / Month"

**Expected Behavior:**
Total alerts displayed in all reports when "Date Range = Month" and "Interval = day / week / month" should match.

**Observed Behavior:**
Total alerts displayed when "Date Range = Month" and "Interval = day / week" match but when "Internal = Month", the total alerts "do not" match.

**Screenshots/Stack Traces:**
Screenshots above would help to visually see the difference in total alerts when "Date Range = Month" and "Interval = day / week / month". 

**Application Version:**
v0.30.1

**Desktop:**
 - OS = MacOS
 - Browser = Chrome
 - Version = 116.0.5845.110 (Official Build) (x86_64)

**Comment by mastercactapus** [comment]
Thanks for the report, the screenshots are helpful. From what you posted here, it looks like the majority of alerts being displayed are in August -- the month view is only showing July.

I think you were expecting to see August in the graph, but it's showing the past month of July

**Comment by dkangala** [comment]
Thank you for prompt response. 

When we (as end-users) keep the "Date Range = Past Month" unchanged and change only the "Interval = Day / Week / Month", my expectation was the "total count of alerts" dispalyed in chart should be same. 

Total count of alerts displayed for following combination were same - this is good:
1) Date Range = Past Month and Interval = Day 
2) Date Range = Past Month and Interval = Week

Total count of alerts displayed for the following combination did not match above - request you to please re-review the screenshots:
3) Date Range = Past Month and Interval = Month

**Comment by mastercactapus** [comment]
I see, so you were expecting the Past Month to include August instead of only July.

In your screenshots:
- Past 5 Weeks is displaying the 5 previous weeks and **omitting the current week**
- Past 1 month is displaying the previous month (July) and **omitting the current month (Aug)**

The data being displayed is accurate from what your screenshots show; however, I think the issue is that omitting the current month entirely is confusing and should probably be reconsidered.

**Comment by mastercactapus** [comment]
The point you bring up about `Date Range` not changing, but changing the interval actually impacts the effective date range, is the most significant reason I think this should be changed.
