### ISSUE TITLE
App heartbeat/version

### ISSUE THREAD

**Issue by Megalon-yx** [target/goalert#3322]
**What problem would you like to solve? Please describe:**
There is no way for my application to tell which version/build of the GoAlert is deployed. 

**Describe the solution you'd like:**
It would be nice if there was some general endpoint like /heartbeat or /version for example, to tell which version of GoAlert is being communicated with.

**Describe alternatives you've considered:**
I tried looking for any descriptions in the documentation of where else the version number might be returned, and even checked content of other calls to see if a version number could be scraped from the response.

**Additional context:**
Our application communicates with GoAlert through the API. For monitoring and traceability reasons, we would prefer to know, at any given point, which version of the GoAlert application we are communicating with. For example, if something that was working suddenly stopped working, is the problem on our end, or are we communicating with a new version that might have a new bug?

**Comment by mastercactapus** [comment]
The deployed version is currently available in meta tags:
![image](https://github.com/target/goalert/assets/595010/b95785c3-5f33-45eb-808a-7ed316ac956c)

It's also embedded in `app.js` so the UI knows when to prompt for refresh.

**Comment by mastercactapus** [comment]
Closing this as it seems it's covered. Feel free to reopen if there's more to discuss!
