### ISSUE TITLE
Disable new user prompt

### ISSUE THREAD

**Issue by bheemvennapureddy** [target/goalert#3621]
**What problem would you like to solve? Please describe:**
All users are requested to add a contact prompt - technically not required for tech ops 

**Describe the solution you'd like:**
if they are not part of Eng team then don't require contact addition 

**Additional context:**
Create a default Eng team and Other team if they fall under other skip contact request.

**Comment by Forfold** [comment]
Hey @bheemvennapureddy, users can simply close out of this dialog if they do not want to add a contact method. However, for a user to receive alerts to their profile, this is highly recommended.

**Comment by bheemvennapureddy** [comment]
@Forfold I had a discussion with @mastercactapus before creating this issue.
