### ISSUE TITLE
tech debt: deprecate stepNumber, use stepIndex

### ISSUE THREAD

**Issue by Forfold** [target/goalert#3872]
We've noticed that the `stepNumber` is used throughout the backend with an index of 0, and on the UI a `stepNumber + 1` is being rendered.

We think that `stepNumber` would be best beginning at `1` from the backend, but since this name is already in use we have decided on deprecating `stepNumber` and using `stepIndex` moving forward, while keeping the index starting with 0. This will help keep GoAlert backwards compatible.

**Comment by c0d33ngr** [comment]
I'll take this

**Comment by Forfold** [comment]
Whoops, I fixed this already but forgot to mark this as completed. Are you looking at good first issues to pickup @c0d33ngr?

**Comment by Forfold** [comment]
Addressed with https://github.com/target/goalert/pull/3916
