### ISSUE TITLE
ui: add error response support for favorite button

### ISSUE THREAD

**Issue by Forfold** [target/goalert#437]
**Is your feature request related to a problem? Please describe:**
Currently, when a user favorites a target (service, rotation, or schedule) and the mutation or query fails, no error message is displayed (`web/src/app/util/QuerySetFavoriteButton.js`).

**Describe the solution you'd like:**
A dialog should be displayed similar to other error dialogs within the application if the user toggles the favorite button and the mutation fails.

If the query fails when loading the page, the star icon should be replaced with an error icon wrapped by a tooltip that will display the error message on hover (see: `Warning` within `web/src/app/icons/components/Icons.js`

**Comment by Quynhd07** [comment]
Fixed in #733. Closing
