### ISSUE TITLE
unique colors for assignments and overrides on schedule calendar

### ISSUE THREAD

**Issue by Forfold** [target/goalert#442]
**Is your feature request related to a problem? Please describe:**
As a user of GoAlert, I want to be able to see which shifts on the calendar are overrides, and which are the regular shifts all at a glance. I also want to know which shifts are from differing assignments, so that if I need to change something or if I need to confirm an override is set up, it is easy to see.

**Describe the solution you'd like:**
- Override events on the calendar are shown in a different color from the default.
- An icon (or something other than just the color) also signifies an override, to ensure colorblind individuals can also see the difference.

**Additional context:**
The query to grab schedule shifts with overrides for the calendar (`schedule(id: ID!)` -> `shifts(start: ISOTimestamp!, end: ISOTimestamp!)` within GraphQL) does not include an indicator on the shift object as to whether or not the shift is an override. Additional work is needed here before reflecting this on the UI.

**Comment by mastercactapus** [comment]
Overrides are now displayed on the calendar component: https://github.com/target/goalert/pull/1901
