### ISSUE TITLE
Add alerting (outgoing) via email (smtp)

### ISSUE THREAD

**Issue by kklemen** [target/goalert#45]
**Is your feature request related to a problem? Please describe:**
No option to send (outgoing) alerts via email; this is a major drawback as emails are still by far the most used channel for sending alerts. Widely supported, very easy to implement.
Imagine a team of 10 support technicians: chances they will all use slack is very slim and sms alerts are very intrusive so should only be sent for critical issues.  Email alerts are standard practice.

**Describe the solution you'd like:**
Add support to send alerts via smtp server (no auth for local relay, plain auth as well as ssl/tls)

**Describe alternatives you've considered:**
None. Alerting by email is an essential feature.

**Comment by s7anley** [comment]
Heya 👋  Do you have this feature in a roadmap? Thanks!

**Comment by m17ch** [comment]
Hi @s7anley -- the team has recently discussed this item and we are interested in introducing this functionality (no ETA, however).

Please feel free to leave a thumbs-up on the original comment if you would find this feature beneficial (it helps us identify what issues/feature suggestions are most desired by the community).

Also, if there are any specifics (or additional details) that you would like to see included with the feature, please feel free to leave a comment with any notes/suggestions.

Thanks!

**Comment by BongoEADGC6** [comment]
@m17ch Good evening, I'd like to start the process here so we may use this internally. Is there any guide documentation for extending these functions?
