### ISSUE TITLE
Rotations not progressing

### ISSUE THREAD

**Issue by s3than** [target/goalert#529]
**Describe the Bug:**
When using a rotation of three days it appears to stop rotating users after at least one rotation.

**Steps to Reproduce:**
1. Create a rotation
2. Set for x days at x oclock
3. See screenshots

**Expected Behavior:**
Rotations work

**Observed Behavior:**
Rotations get stuck

**Screenshots/Stack Traces:**
If applicable, add screenshots and/or stack traces to help explain your problem.

![test](https://user-images.githubusercontent.com/6881648/76724784-ea7cee00-6797-11ea-9a55-a3c673170c58.png)
![test1](https://user-images.githubusercontent.com/6881648/76724787-ebae1b00-6797-11ea-9b89-6de6cbf9064d.png)

**Application Version:**
Output of `goalert version` and/or version information from view-source on the UI.

`
$ goalert version
...
v0.24.1
...

**Comment by s3than** [comment]
When updating the rotation to a new user the following start and end times are passed.

```
{"data":{"updateRotation":true},"extensions":{"tracing":{"version":1,"startTime":"2020-03-16T05:15:53.07814015Z","endTime":"2020-03-16T05:15:53.079687949Z","duration":1547747,"execution":{"resolvers":[{"path":["updateRotation"],"parentType":"Mutation","fieldName":"updateRotation","returnType":"Boolean!","startOffset":10209,"duration":1532747}]}}}}
```

**Comment by s3than** [comment]
Deleting all users in the rotation and re-entering them resets, I can see the following in the logs

```
{"AuthSystemComponent":"Engine","SQLErrDetails":"Failing row contains (05e26abb-2484-4402-a2b1-a4e1fbedbad7, 1, null, 2020-03-16 05:47:31.289985+00, 80).","Trigger":"INTERVAL","error":"Engine.RotationManager: advance rotation: ERROR: null value in column \"rotation_participant_id\" violates not-null constraint (SQLSTATE 23502)","level":"error","msg":"","time":"2020-03-16T05:47:31Z"}
{"AuthSystemComponent":"Engine","Trigger":"INTERVAL","level":"info","msg":"Engine cycle end.","time":"2020-03-16T05:47:31Z"}
```

**Comment by s3than** [comment]
Locating the rotation and resetting those users clears up everyone elses and the rotations start again. Still trying to workout what was wrong with that rotation though.

However the main issue is that if there is an error it locks all other rotations from proceeding

**Comment by Forfold** [comment]
Hey @s3than, I'm planning on digging into this a bit today. Just to clarify, after you deleted all of the users in the rotation and re-entered them again, did you see that the rotation was able to rotate properly or did it get stuck again after the first rotation? Have you seen this occur on any other handoff types (hourly/weekly)? Just looking to get some additional context before I get started, thanks!

**Comment by s3than** [comment]
Once we removed the users associated with the rotation they all started rotating again with out any issues.

**Comment by Forfold** [comment]
Gotcha, if it comes up again could you try refreshing the UI to verify that we're seeing the same issue? I'll be working on the UI fix for the time being, though 😄

**Comment by s3than** [comment]
@Forfold The backend issue occurred again and was triggered from the same group of two users in a rotation.

**Comment by s3than** [comment]
```
{"AuthSystemComponent":"Engine","SQLErrDetails":"Failing row contains (05e26abb-2484-4402-a2b1-a4e1fbedbad7, 1, null, 2020-03-28 07:03:56.909997+00, 104).","Trigger":"INTERVAL","error":"Engine.RotationManager: advance rotation: ERROR: null value in column \"rotation_participant_id\" violates not-null constraint (SQLSTATE 23502)","level":"error","msg":"","time":"2020-03-28T07:03:56Z"}
```

Occurred again, I'm going to delete the users and recreate them and see if still occurs.

**Comment by Forfold** [comment]
Hey @s3than, we did some investigating and have not been able to reproduce the scenario you've outlined. Would you be able to provide us a step by step list of instructions for how to reproduce? Has it occurred anymore since back in March?

**Comment by s3than** [comment]
@Forfold Thanks for getting back to me, it was intermittent over a month. However I deleted the rotation that it was getting stuck on, created a brand new one with a slightly different naming convention and it hasn't occurred again. 

Unfortunately I haven't got a record of what the previous name was other than it started with a space. (No I don't know why that was the case) I'll close this one off though.

Thanks again.

**Comment by Forfold** [comment]
@s3than Sounds good. If it ever comes up again please don't hesitate to let us know and we can try and find the root of the cause 😄
