### ISSUE TITLE
FR: Rotation/handoff notifications

### ISSUE THREAD

**Issue by prestonvanloon** [target/goalert#583]
**Is your feature request related to a problem? Please describe:**
N/A

**Describe the solution you'd like:**
I would like to send an email or other notification when a user becomes the oncall in a rotation schedule.

**Describe alternatives you've considered:**
I don't think there is any support for this yet.

**Additional context:**

**Comment by AdamLWestman** [comment]
Hi @prestonvanloon thanks for the feature submission.  Yes, this is definitely something we want to add.  

For starters to address your request, we plan on adding calendar subscriptions.  With the subscription, you can include your GoAlert on-call schedule on a calendar app of your choice (Google Calendar, on your iPhone, Android device...basically anything that supports the iCal format).  In this way, you'll be able to also create reminders before you go on call in whatever native way you are doing today.

We are working on calendar subscriptions now.  Looks for an update from us soon. 

Thanks again for the submission!

**Comment by prestonvanloon** [comment]
@AdamLWestman Thanks! Calendar subscriptions would be very helpful.

**Comment by HenkeRobert** [comment]
Also any chance we could allow alerting if there's a change in the future schedule rotation?  Folks are eager to get an alert if their future holidays are affected when folks add/remove from the on-call roster.  Thanks so much, and let me know if you'd prefer a different issue added.

**Comment by AdamLWestman** [comment]
@prestonvanloon Calendar subscriptions is how available in the latest GoAlert release: https://github.com/target/goalert/releases/tag/v0.25.0 

Please let me know what questions you have.

**Comment by prestonvanloon** [comment]
This works for me! We've updated to v0.25.0 and subscribed to calendars events. I now see these calendar events!

OK to close from me, I think @HenkeRobert has a great idea though. I'll defer to you @AdamLWestman on closing this FR.

**Comment by AdamLWestman** [comment]
Thanks @prestonvanloon for confirmation.  Glad this works for you! 👍   

@HenkeRobert could you open a new issue for the rotation notification feature?
