### ISSUE TITLE
Ability to sort by alert date when querying alerts via the Graphql API

### ISSUE THREAD

**Issue by craigatk** [target/goalert#714]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**
I'm using the Graphql API to find off-hours alerts in the past 7 days to bring visibility to the number of alerts in the teams I work with and potentially reduce false positives. I queried for the paged alerts using the API and stopped once I reach alerts 7 days old but the alerts are currently sorted by status (closed alerts are last) and not date so I was missing closed alerts that came at the end of the query results.

It'd be a big help if I could tell the API to sort by alert date when querying by alerts.

**Describe alternatives you've considered:**
Currently I've worked around this issue by querying separately for closed alerts and joining them back to the main list, but that's a bit messy and is also adding extra queries and extra load on the API.

**Comment by mastercactapus** [comment]
@craigatk Can you take a look at that PR and confirm that it would work for your use-case?

**Comment by craigatk** [comment]
@mastercactapus I took a look at the PR and the option to sort by date as well as the bonus of excluding all alerts before a certain date would definitely work for my use case - thanks!
