### ISSUE TITLE
Admin/Config should collapse sections by default

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#796]
**Is your feature request related to a problem? Please describe:**
The admin config page has gotten very long, making it time consuming to get to the desired section.

**Describe the solution you'd like:**
An accordion style, one section expanded at a time. With everything collapsed by default.

Each section could have a chip/summary of the number of changes it contains before hitting save.

**Describe alternatives you've considered:**
N/A

**Additional context:**
N/A

**Comment by mastercactapus** [comment]
A possible/proposed approach in the `admin-accordion` branch

![image](https://user-images.githubusercontent.com/595010/88416978-bf8a5280-cda6-11ea-86ca-9c5f00e013be.png)

- Highlight values that have been changed/unsaved in the current section
- Collapsed by default
- Sections that have an "Enable" value called out in secondary text
- Summary of number of changes when a section has been updated (but not saved)

TODO:
- Update cypress tests

Other Thoughts:
- Instead of (or in addition to) add proper section descriptions -- would need new API, however
- Anchor/linkable sections (e.g. `/admin#Twilio` would expand and scroll to the Twilio section)

@Forfold What are your thoughts?

**Comment by Forfold** [comment]
That looks awesome! Maybe we could make the fields that have been edited a little more subtle? Perhaps a lighter yellow or some icon? I like the concept of using accordions though now that we have more sections, and showing the chip with outstanding changes per section!

**Comment by mastercactapus** [comment]
Yeah I agree (those styling was never my strong suit lol) -- maybe 200 or 100, just so it's scannable to find changes

Thanks for the feedback 😊
