### ISSUE TITLE
material select: input not cleared on blur (regression)

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#920]
**Describe the Bug:**
When a material select field loses focus the filter input should be blank (or the selected value for single-selects).

**Steps to Reproduce:**
1. Go to Services page
2. Click add `+` button
3. Type a search string like "foo" in the Escalation Policy field
4. Click on a different field
5. Observe the search string persists

**Expected Behavior:**
The search string should clear when the field loses focus

**Observed Behavior:**
The search string persists when the field loses focus

**Application Version:**
Output of `goalert version` and/or version information from view-source on the UI.

```
$ goalert version
Version:   v0.25.0-424-ga808c9e7
GitCommit: a808c9e7682516350be1ea4d4b7badc66d98dfda (clean)
BuildDate: 2020-10-07T07:59:00-05:00
GoVersion: go1.15.2 (gc)
Platform:  linux/amd64
Migration: session-last-access-time (#200)
```

**Comment by Forfold** [comment]
Created #958 to continue this work, commenting for cross-reference
