### ISSUE TITLE
Missing app.js after buidling from source.

### ISSUE THREAD

**Issue by laurent-8** [target/goalert#926]
**Describe the Bug:**
After building Goalert from source, when running the service the web ui seems broken. 
The service itself runs fine but when loading the web ui only a white screen appears. 
When inspecting the html it seems script /static/app.js is missing. 

**Observed Behavior:**
White screen when loading Goalert web ui

**Screenshots/Stack Traces:**
![image](https://user-images.githubusercontent.com/67110048/95462091-55318900-0977-11eb-9e3f-a50bd7677020.png)

**Application Version:**
v0.25.0-268-ge22781d4

**Comment by mastercactapus** [comment]
If you are trying to build a ready-to-deploy binary add `BUNDLE=1` to the end like: `make bin/goalert BUNDLE=1`

If you're doing local development run `make start` which will start GoAlert, tracing, and the UI dev server

Most relevant commands are in the dev guide:
https://github.com/target/goalert/blob/master/docs/development-setup.md#toolchain-requirements

Setting `BUNDLE=1` will cause the UI to be built and packaged into the `goalert` binary

**Comment by laurent-8** [comment]
It's working now. Totally missed that in the docs.
Thanks!
