### ISSUE TITLE
ui/alert logs: adjust time between escalations column

### ISSUE THREAD

**Issue by Forfold** [target/goalert#932]
**Describe the Bug:**
After an escalation policy has fully processed an alert through all steps, the table from the alert details shows all values in the "Time Between Escalations" column as `—`. This should likely change to something more meaningful.

**Steps to Reproduce:**
1. Create an alert
2. Visit the alert's details
3. Wait for the alert to finish escalating (or manually escalate)
4. See results as shown below: 

**Screenshots/Stack Traces:**
![image](https://user-images.githubusercontent.com/11381794/95777359-e5731500-0c7a-11eb-9b0f-dde50d870caa.png)

**Possible Solutions:**
- Rename column title to "Escalation Info"
- Change `—` to the timestamp of when that step last escalated
- If a step is not currently active or has not been escalated yet, display "Awaiting escalation" or similar
- Truncate countdown text, in favor of terse wording, using exact seconds if < 1 minute remaining
    - i.e. `4m`, `1h`, or `48s`
- Display text after the countdown string, displaying as "4m until next escalation"
- Display countdown text of fully escalated steps as "Fully escalated" or similar (i.e. a step that fulfills the EP's repeat count)

**Comment by mastercactapus** [comment]
Maybe we should prefix it? We also need to handle repeats.

```
Last escalated at: ....
Last escalated at: ....
Will escalate in: 4m
Will escalate (repeat) in: 4m
```

Alternatively, so it's less noisy, we could dedicate the space to `Step` and `Alert` (or maybe `To Notify`) and get rid of the `Time Between Escalations` entirely. Originally this was here because an alert contained a snapshot of the policy, but that's no longer the case.

We could then just have a spot on this card that says `Last Escalated: <timestamp>, Next Escalation: 4m`

**Comment by Forfold** [comment]
I think it makes sense to just show last escalation/next escalation since we no longer have the snapshot available to us, though it's important we retain highlighting the current step it's on

**Comment by Forfold** [comment]
It looks like we also don't show slack channels and the column is left blank, so we should handle that as well
